/**
 * Generated by sync-artifacts.cjs — DO NOT EDIT MANUALLY.
 * Networks: celoSepolia (11142220), celo (42220)
 */

import _addresses from './addresses.json';
import abis from './abis.json';

const addresses = _addresses as Record<string, Record<string, string>>;

export const CONTRACTS = {
  ImpactPay: {
    address: addresses.ImpactPay as Record<number, `0x${string}`>,
    abi: abis.ImpactPay,
  },
  MockERC20: {
    address: addresses.MockERC20 as Record<number, `0x${string}`>,
    abi: abis.MockERC20,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
