/**
 * Generated by sync-artifacts.js — DO NOT EDIT MANUALLY.
 * Source: blockchain/deployments/celoSepolia/
 */

import _addresses from './addresses.json';
import abis from './abis.json';

const addresses = _addresses as Record<string, string>;

export const CONTRACTS = {
  ImpactPay: {
    address: addresses.ImpactPay as `0x${string}`,
    abi: abis.ImpactPay,
  },
  MockERC20: {
    address: addresses.MockERC20 as `0x${string}`,
    abi: abis.MockERC20,
  },
} as const;

export type ContractName = keyof typeof CONTRACTS;
